version: 0.0
os: linux
files:
   - source: /
     destination: /home/node-fe/test-web-app
permissions:
   - object: /home/node-fe/test-web-app
     pattern: "**"
     owner: node-fe
     group: node-fe
     mode: 755
     type:
       - file
hooks:
   BeforeInstall:
    - location: scripts/before_install.sh
      runas: root
   AfterInstall:
    - location: scripts/after_install.sh
      runas: root
